name: 'neorv32-verilog verification'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:

  Verification:
    runs-on: ubuntu-latest

    steps:

    - name: '📂 Repository Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '📦 Install Icarus Verilog'
      run: |
        wget https://github.com/stnolting/icarus-verilog-prebuilt/releases/download/v1.0.0/iverilog-27082022.tar.gz
        mkdir $GITHUB_WORKSPACE/iverilog-27082022.tmp
        tar -xzf iverilog-27082022.tar.gz -C $GITHUB_WORKSPACE/iverilog-27082022.tmp/

    - name: '⚙️ Update PATH variable'
      run: echo "$GITHUB_WORKSPACE/iverilog-27082022.tmp/bin" >> $GITHUB_PATH

    - name: '📦 Install GHDL'
      uses: ghdl/setup-ghdl-ci@nightly

    - name: '🚀 Run check script'
      run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/.github/check.sh && $GITHUB_WORKSPACE/.github/check.sh"

