name: 'neorv32-verilog check'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:


jobs:

  convert:
    name: '♻️ Convert to Verilog'
    runs-on: ubuntu-latest

    steps:

    - name: '📂 Repository Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '📦 Install GHDL'
      uses: ghdl/setup-ghdl@v1
      with:
        version: nightly
        backend: mcode

    - name: '⚙️ Run conversion'
      run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/src/convert.sh && $GITHUB_WORKSPACE/src/convert.sh"

    - name: '📤 Archive generated Verilog code'
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: neorv32_verilog_code
        path: src/neorv32_verilog_wrapper.v


  sim_iverilog:
    name: '🖥️ Simulation - Icarus Verilog'
    needs: convert
    runs-on: ubuntu-latest

    steps:

    - name: '📦 Install Icarus Verilog'
      run: sudo apt install iverilog

    - name: '⚙️ Run verification script'
      run: |
        make -C sim SIM=iverilog


  sim_verilator:
    name: '🖥️ Simulation - Verilator'
    needs: convert
    runs-on: ubuntu-latest

    steps:

    - name: '📦 Install Verilator'
      run: sudo apt install verilator

    - name: '⚙️ Run verification script'
      run: |
        make -C sim SIM=verilator
